import 'package:flutter/material.dart';

class AppLocalization extends ChangeNotifier {
  static final AppLocalization _instance = AppLocalization._internal();
  factory AppLocalization() => _instance;
  AppLocalization._internal();

  String _currentLanguageCode = 'en';
  String get currentLanguageCode => _currentLanguageCode;

  void setLanguage(String code) {
    if (_translations.containsKey(code)) {
      _currentLanguageCode = code;
    } else {
      _currentLanguageCode = 'en';
    }
    notifyListeners();
  }

  String t(String key, [String? fallback]) {
    final langMap = _translations[_currentLanguageCode];
    if (langMap != null && langMap.containsKey(key)) {
      return langMap[key]!;
    }
    final enMap = _translations['en'];
    if (enMap != null && enMap.containsKey(key)) {
      return enMap[key]!;
    }
    return fallback ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'brandTitle': 'MediConnect',
      'brandSubtitle': 'AI Hyperlocal Health Assistant & Pharmacy',
      'guardLabel': 'Guard',
      'verifiedPatient': 'Verified Patient',
      'storeOwner': 'Pharmacy Store Owner',
      'guardAspirinBlocked': 'Guard: Aspirin Blocked',
      'autoPayCap': 'Auto-Pay Cap',
      'safeAutoPayTitle': 'Safe Auto-Pay Limit Guardrail',
      'safeAutoPayDesc': 'Any medicine order exceeding this threshold requires 2-step manual approval.',
      'currentBalance': 'Current Auto-Pay Limit',
      'addAmount': '+ Add Amount',
      'topUpSuccess': 'Successfully added to Safe Auto-Pay Limit!',
      'tabTriage': 'Triage',
      'tabStores': 'Pharmacies',
      'tabOrders': 'Orders',
      'tabCard': 'Health Card',
      'tabSos': 'SOS',
      'signOutBtn': 'Sign Out',
      'emergencyBtn': 'Emergency SOS',
      'voiceTitle': 'Where does it hurt? (क्या तकलीफ है?)',
      'voiceDesc': 'Tap the microphone to speak naturally or describe your symptoms below:',
      'micTap': 'Tap to Speak Symptoms',
      'micListening': 'Listening in real-time... Speak now',
      'symptomPlaceholder': "Describe health issue: e.g. 'I have a headache and sore throat since morning'...",
      'consultBtn': 'Consult AI Agents',
      'headache': 'Headache / Body Pain',
      'headacheSub': 'Aspirin-safe pain relief',
      'cold': 'Cold & Sore Throat',
      'coldSub': 'Warm remedies & steam',
      'acidity': 'Stomach Gas & Acidity',
      'aciditySub': 'Instant antacid relief',
      'chestPain': 'Severe Chest Pain (Emergency)',
      'chestPainSub': 'Immediate Ambulance SOS',
      'changeLocationBtn': 'Change Location 📍',
      'selectLocationTitle': 'Select Location',
      'selectLocationSub': 'Auto-detect via GPS or enter delivery address manually',
      'locTabMap': '🗺️ Google Maps',
      'locTabGps': '🛰️ Auto GPS',
      'locTabManual': '✏️ Manual Entry',
      'btnAutoDetectGps': '📍 Auto-Detect via GPS',
      'saveLocationBtn': 'Save Delivery Location',
      'addressLabel': 'Delivery Address',
      'cityLabel': 'City / Town',
      'pincodeLabel': 'PIN Code',
      'trustedStoresTitle': '🏥 Trusted Nearby Medical Stores',
      'searchStorePlaceholder': 'Search medicine (e.g. Paracetamol, Cetirizine)...',
      'searchStoresBtn': 'Search Stores',
      'inStock': 'In Stock',
      'orderDelivery': 'Order for Delivery',
      'callShop': '📞 Call Shop',
      'chatChemist': '💬 Chat with Chemist',
      'healthCardTitle': '🛡️ Safe Health Profile & Guardrails',
      'healthCardSub': 'AES-256 encrypted medical records, allergy denylist, and server-side payment protection limit.',
      'patientProfile': 'Patient Profile',
      'nameLabel': 'Full Name',
      'phoneLabel': 'Mobile Number',
      'emailLabel': 'Email Address',
      'allergiesLabel': 'Encrypted Allergies (At Rest)',
      'addAllergyBtn': '+ Add & Encrypt Allergy',
      'editProfileBtn': '✏️ Edit Health Card Details',
      'saveChangesBtn': '✓ Save Changes',
      'cancelBtn': 'Cancel',
      'ordersTitle': '📦 Orders & Booked Appointments',
      'orderedMedsLabel': '💊 Ordered Medicines',
      'bookedApptsLabel': '🏥 Booked Appointments',
      'loginGoogle': 'Continue with Google',
      'loginEmailDirect': 'Login with Email Directly',
      'forgotPasswordTitle': 'Forgot Password?',
      'sendResetCodeBtn': 'Send Verification Code to Gmail',
      'verifyAndResetBtn': 'Verify Code & Reset Password',
    },
    'hi': {
      'brandTitle': 'मेडीकनेक्ट',
      'brandSubtitle': 'एआई हाइपरलोकल स्वास्थ्य सहायक और फार्मेसी',
      'guardLabel': 'सुरक्षा',
      'verifiedPatient': 'सत्यापित मरीज',
      'storeOwner': 'दवा दुकान संचालक',
      'guardAspirinBlocked': 'गार्ड: एस्पिरिन ब्लॉक',
      'autoPayCap': 'ऑटो-पे सीमा',
      'safeAutoPayTitle': 'सुरक्षित ऑटो-पे सीमा (गार्डरेल)',
      'safeAutoPayDesc': 'इस सीमा से अधिक का कोई भी दवा ऑर्डर मैन्युअल स्वीकृति मांगता है।',
      'currentBalance': 'वर्तमान ऑटो-पे सीमा',
      'addAmount': '+ राशि जोड़ें',
      'topUpSuccess': 'ऑटो-पे सीमा में राशि सफलतापूर्वक जोड़ी गई!',
      'tabTriage': 'जांच व सलाह',
      'tabStores': 'दवा दुकानें',
      'tabOrders': 'ऑर्डर्स',
      'tabCard': 'हेल्थ कार्ड',
      'tabSos': 'आपातकालीन',
      'signOutBtn': 'लॉग आउट',
      'emergencyBtn': 'आपातकालीन एसओएस',
      'voiceTitle': 'आपको क्या तकलीफ है? (कहाँ दर्द है?)',
      'voiceDesc': 'माइक दबाकर बोलें या नीचे अपने लक्षण लिखें:',
      'micTap': 'बोलने के लिए माइक दबाएं',
      'micListening': 'रीयल-टाइम में सुन रहे हैं... अब बोलें',
      'symptomPlaceholder': 'अपनी समस्या बताएं: जैसे मुझे सुबह से सिरदर्द और बुखार है...',
      'consultBtn': 'एआई से परामर्श लें',
      'headache': 'सिर दर्द / बदन दर्द',
      'headacheSub': 'एस्पिरिन-मुक्त दर्द निवारक',
      'cold': 'सर्दी और गले में खराश',
      'coldSub': 'गरम उपचार और भाप',
      'acidity': 'पेट गैस और एसिडिटी',
      'aciditySub': 'तुरंत एंटासिड आराम',
      'chestPain': 'सीने में तेज दर्द (आपातकालीन)',
      'chestPainSub': 'तत्काल एम्बुलेंस एसओएस',
      'changeLocationBtn': 'स्थान बदलें 📍',
      'selectLocationTitle': 'स्थान चुनें',
      'selectLocationSub': 'जीपीएस द्वारा खोजें या मैन्युअल पता दर्ज करें',
      'locTabMap': '🗺️ गूगल मैप्स',
      'locTabGps': '🛰️ ऑटो जीपीएस',
      'locTabManual': '✏️ मैन्युअल पता',
      'btnAutoDetectGps': '📍 जीपीएस से मेरा स्थान खोजें',
      'saveLocationBtn': 'डिलीवरी स्थान सहेजें',
      'addressLabel': 'डिलीवरी का पता',
      'cityLabel': 'शहर / कस्बा',
      'pincodeLabel': 'पिन कोड',
      'trustedStoresTitle': '🏥 नजदीकी विश्वसनीय मेडिकल स्टोर',
      'searchStorePlaceholder': 'दवा खोजें (उदा. पैरासिटामोल, सेट्रिजीन)...',
      'searchStoresBtn': 'स्टोर खोजें',
      'inStock': 'स्टॉक उपलब्ध',
      'orderDelivery': 'डिलीवरी के लिए ऑर्डर करें',
      'callShop': '📞 दुकान पर कॉल करें',
      'chatChemist': '💬 केमिस्ट से चैट करें',
      'healthCardTitle': '🛡️ सुरक्षित स्वास्थ्य प्रोफाइल और गार्डरेल',
      'healthCardSub': 'AES-256 एन्क्रिप्टेड रिकॉर्ड, एलर्जी प्रतिबंध सूची और भुगतान सुरक्षा सीमा।',
      'patientProfile': 'मरीज प्रोफाइल',
      'nameLabel': 'पूरा नाम',
      'phoneLabel': 'मोबाइल नंबर',
      'emailLabel': 'ईमेल पता',
      'allergiesLabel': 'एन्क्रिप्टेड एलर्जी',
      'addAllergyBtn': '+ एलर्जी जोड़ें और एन्क्रिप्ट करें',
      'editProfileBtn': '✏️ हेल्थ कार्ड विवरण बदलें',
      'saveChangesBtn': '✓ बदलाव सहेजें',
      'cancelBtn': 'रद्द करें',
      'ordersTitle': '📦 ऑर्डर्स और अपॉइंटमेंट',
      'orderedMedsLabel': '💊 ऑर्डर की गई दवाएं',
      'bookedApptsLabel': '🏥 बुक किए गए अपॉइंटमेंट',
      'loginGoogle': 'गूगल से लॉगिन करें',
      'loginEmailDirect': 'ईमेल से सीधा लॉगिन करें',
      'forgotPasswordTitle': 'पासवर्ड भूल गए?',
      'sendResetCodeBtn': 'जीमेल पर कोड भेजें',
      'verifyAndResetBtn': 'कोड सत्यापित करें और पासवर्ड बदलें',
    },
    'te': {
      'brandTitle': 'మెడికనెక్ట్',
      'brandSubtitle': 'AI స్థానిక ఆరోగ్య సహాయకుడు & మందుల దుకాణం',
      'guardLabel': 'రక్షణ',
      'verifiedPatient': 'ధృవీకరించబడిన రోగి',
      'storeOwner': 'మెడికల్ షాప్ యజమాని',
      'guardAspirinBlocked': 'గార్డ్: ఆస్పిరిన్ నిరోధించబడింది',
      'autoPayCap': 'ఆటో-పే పరిమితి',
      'safeAutoPayTitle': 'సురక్షిత ఆటో-పే పరిమితి గార్డ్‌రైల్',
      'safeAutoPayDesc': 'ఈ పరిమితి మించిన ఆర్డర్లకు ప్రత్యేక ఆమోదం అవసరం.',
      'currentBalance': 'ప్రస్తుత ఆటో-పే పరిమితి',
      'addAmount': '+ మొత్తం జోడించండి',
      'topUpSuccess': 'ఆటో-పే పరిమితికి మొత్తం విజయవంతంగా జోడించబడింది!',
      'tabTriage': 'ఆరోగ్య సలహా',
      'tabStores': 'మందుల షాపులు',
      'tabOrders': 'ఆర్డర్లు',
      'tabCard': 'హెల్త్ కార్డ్',
      'tabSos': 'అత్యవసరం',
      'signOutBtn': 'లాగ్ అవుట్',
      'emergencyBtn': 'అత్యవసర SOS',
      'voiceTitle': 'మీకు ఎక్కడ నొప్పిగా ఉంది? (ఆరోగ్య సమస్య)',
      'voiceDesc': 'మైక్ నొక్కి మాట్లాడండి లేదా కింద మీ లక్షణాలను రాయండి:',
      'micTap': 'మాట్లాడటానికి మైక్ నొక్కండి',
      'micListening': 'వినబడుతోంది... ఇప్పుడు మాట్లాడండి',
      'symptomPlaceholder': 'మీ సమస్యను చెప్పండి: ఉదా. నాకు ఉదయం నుండి తలనొప్పిగా ఉంది...',
      'consultBtn': 'AI సంప్రదించండి',
      'headache': 'తల నొప్పి / ఒంటి నొప్పులు',
      'headacheSub': 'ఆస్పిరిన్-రహిత నొప్పి నివారణ',
      'cold': 'జలుబు & గొంతు నొప్పి',
      'coldSub': 'వెచ్చని చిట్కాలు & ఆవిరి',
      'acidity': 'కడుపు మంట & గ్యాస్',
      'aciditySub': 'తక్షణ యాంటాసిడ్ ఉపశమనం',
      'chestPain': 'తీవ్రమైన ఛాతీ నొప్పి (అత్యవసరం)',
      'chestPainSub': 'తక్షణ అంబులెన్స్ SOS',
      'changeLocationBtn': 'స్థానం మార్చండి 📍',
      'selectLocationTitle': 'స్థానాన్ని ఎంచుకోండి',
      'selectLocationSub': 'GPS ఆటో-గుర్తింపు లేదా మాన్యువల్ చిరునామా',
      'locTabMap': '🗺️ గూగుల్ మ్యాప్స్',
      'locTabGps': '🛰️ ఆటో GPS',
      'locTabManual': '✏️ మాన్యువల్ ఎంట్రీ',
      'btnAutoDetectGps': '📍 GPS ద్వారా నా స్థానాన్ని గుర్తించండి',
      'saveLocationBtn': 'డెలివరీ స్థానాన్ని సేవ్ చేయండి',
      'addressLabel': 'డెలివరీ చిరునామా',
      'cityLabel': 'నగరం / గ్రామం',
      'pincodeLabel': 'పిన్ కోడ్',
      'trustedStoresTitle': '🏥 సమీప విశ్వసనీయ మెడికల్ దుకాణాలు',
      'searchStorePlaceholder': 'మందును వెతకండి (ఉదా. పారాసిటమాల్)...',
      'searchStoresBtn': 'షాపులను వెతకండి',
      'inStock': 'స్టాక్ ఉంది',
      'orderDelivery': 'డెలివరీ కోసం ఆర్డర్ చేయండి',
      'callShop': '📞 షాపుకు కాల్ చేయండి',
      'chatChemist': '💬 కెమిస్ట్‌తో చాట్ చేయండి',
      'healthCardTitle': '🛡️ సురక్షిత హెల్త్ కార్డ్ & రక్షణ పరిమితి',
      'healthCardSub': 'AES-256 ఎన్‌క్రిప్టెడ్ రికార్డులు మరియు రక్షణ పరిమితి.',
      'patientProfile': 'పేషెంట్ ప్రొఫైల్',
      'nameLabel': 'పూర్తి పేరు',
      'phoneLabel': 'మొబైల్ సంఖ్య',
      'emailLabel': 'ఈమెయిల్ చిరునామా',
      'allergiesLabel': 'ఎన్‌క్రిప్ట్ చేసిన అలెర్జీలు',
      'addAllergyBtn': '+ అలెర్జీని జోడించి ఎన్‌క్రిప్ట్ చేయండి',
      'editProfileBtn': '✏️ హెల్త్ కార్డ్ వివరాలను మార్చండి',
      'saveChangesBtn': '✓ మార్పులను సేవ్ చేయండి',
      'cancelBtn': 'రద్దు చేయండి',
      'ordersTitle': '📦 ఆర్డర్లు & అపాయింట్‌మెంట్లు',
      'orderedMedsLabel': '💊 ఆర్డర్ చేసిన మందులు',
      'bookedApptsLabel': '🏥 బుక్ చేసిన అపాయింట్‌మెంట్లు',
      'loginGoogle': 'గూగుల్‌తో లాగిన్ అవ్వండి',
      'loginEmailDirect': 'ఈమెయిల్‌తో నేరుగా లాగిన్ అవ్వండి',
      'forgotPasswordTitle': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'sendResetCodeBtn': 'Gmail కి కోడ్ పంపండి',
      'verifyAndResetBtn': 'కోడ్ ధృవీకరించి పాస్‌వర్డ్ మార్చండి',
    },
    'ta': {
      'brandTitle': 'மெடிகனெக்ட்',
      'brandSubtitle': 'AI உள்ளூர் சுகாதார உதவியாளர் & மருந்தகம்',
      'guardLabel': 'பாதுகாப்பு',
      'verifiedPatient': 'சரிபார்க்கப்பட்ட நோயாளி',
      'storeOwner': 'மருந்தக உரிமையாளர்',
      'guardAspirinBlocked': 'பாதுகாப்பு: ஆஸ்பிரின் தடுக்கப்பட்டது',
      'autoPayCap': 'தானியங்கி கட்டண வரம்பு',
      'safeAutoPayTitle': 'பாதுகாப்பான கட்டண வரம்பு',
      'safeAutoPayDesc': 'இந்த வரம்பிற்கு மேற்பட்ட ஆர்டர்களுக்கு ஒப்புதல் தேவை.',
      'currentBalance': 'தற்போதைய கட்டண வரம்பு',
      'addAmount': '+ தொகையைச் சேர்',
      'topUpSuccess': 'வரம்பில் தொகை வெற்றிகரமாக சேர்க்கப்பட்டது!',
      'tabTriage': 'பரிசோதனை',
      'tabStores': 'மருந்தகங்கள்',
      'tabOrders': 'ஆர்டர்கள்',
      'tabCard': 'சுகாதார அட்டை',
      'tabSos': 'அவசரம்',
      'signOutBtn': 'வெளியேறு',
      'emergencyBtn': 'அவசர SOS',
      'voiceTitle': 'உங்களுக்கு எங்கு வலிக்கிறது?',
      'voiceDesc': 'மைக் பொத்தானை அழுத்தி பேசவும்:',
      'micTap': 'பேச மைக் அழுத்தவும்',
      'micListening': 'கேட்கிறது... இப்போது பேசுங்கள்',
      'symptomPlaceholder': 'உங்கள் பிரச்சனையை விவரிக்கவும்...',
      'consultBtn': 'AI ஆலோசனை பெறுங்கள்',
      'headache': 'தலைவலி / உடல் வலி',
      'headacheSub': 'ஆஸ்பிரின்-பாதுகாப்பான வலி நிவாரணம்',
      'cold': 'சளி மற்றும் தொண்டை வலி',
      'coldSub': 'சூடான வைத்தியம் & நீராவி',
      'acidity': 'வயிற்று வலி & வாயு',
      'aciditySub': 'உடனடி அசிடிட்டி நிவாரணம்',
      'chestPain': 'கடுமையான நெஞ்சு வலி (அவசரம்)',
      'chestPainSub': 'உடனடி ஆம்புலன்ஸ் SOS',
      'changeLocationBtn': 'இடத்தை மாற்றவும் 📍',
      'selectLocationTitle': 'இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
      'selectLocationSub': 'GPS அல்லது கைமுறை முகவரி',
      'locTabMap': '🗺️ கூகிள் மேப்ஸ்',
      'locTabGps': '🛰️ ஆட்டோ ஜிபிஎஸ்',
      'locTabManual': '✏️ கைமுறை முகவரி',
      'btnAutoDetectGps': '📍 ஜிபிஎஸ் மூலம் எனது இருப்பிடம் கண்டறி',
      'saveLocationBtn': 'டெலிவரி இருப்பிடத்தைச் சேமி',
      'addressLabel': 'டெலிவரி முகவரி',
      'cityLabel': 'நகரம் / கிராமம்',
      'pincodeLabel': 'அஞ்சல் குறியீடு',
      'trustedStoresTitle': '🏥 அருகிலுள்ள நம்பகமான மருந்தகங்கள்',
      'searchStorePlaceholder': 'மருந்தைத் தேடுங்கள்...',
      'searchStoresBtn': 'கடைகளைத் தேடுங்கள்',
      'inStock': 'இருப்பு உள்ளது',
      'orderDelivery': 'டெலிவரிக்கு ஆர்டர் செய்யுங்கள்',
      'callShop': '📞 கடைக்கு அழைக்கவும்',
      'chatChemist': '💬 மருந்தாளருடன் அரட்டையடிக்கவும்',
      'healthCardTitle': '🛡️ பாதுகாப்பான சுகாதார அட்டை',
      'healthCardSub': 'AES-256 குறியாக்கப்பட்ட பதிவுகள் மற்றும் பாதுகாப்பு வரம்பு.',
      'patientProfile': 'நோயாளி சுயவிவரம்',
      'nameLabel': 'முழுப் பெயர்',
      'phoneLabel': 'மொபைல் எண்',
      'emailLabel': 'மின்னஞ்சல் முகவரி',
      'allergiesLabel': 'ஒவ்வாமைகள்',
      'addAllergyBtn': '+ ஒவ்வாமை சேர்க்கவும்',
      'editProfileBtn': '✏️ விவரங்களைத் திருத்துக',
      'saveChangesBtn': '✓ மாற்றங்களைச் சேமி',
      'cancelBtn': 'ரத்து செய்',
      'ordersTitle': '📦 ஆர்டர்கள் & முன்பதிவுகள்',
      'orderedMedsLabel': '💊 ஆர்டர் செய்த மருந்துகள்',
      'bookedApptsLabel': '🏥 முன்பதிவுகள்',
      'loginGoogle': 'கூகிள் மூலம் உள்நுழைக',
      'loginEmailDirect': 'மின்னஞ்சல் மூலம் நேரடியாக உள்நுழைக',
      'forgotPasswordTitle': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'sendResetCodeBtn': 'Gmail-க்கு குறியீடு அனுப்பவும்',
      'verifyAndResetBtn': 'சரிபார்த்து கடவுச்சொல்லை மாற்றவும்',
    },
    'bn': {
      'brandTitle': 'মেডিকানেক্ট',
      'brandSubtitle': 'এআই স্বাস্থ্য সহকারী এবং ফার্মেসি',
      'guardLabel': 'সুরক্ষা',
      'verifiedPatient': 'যাচাইকৃত রোগী',
      'storeOwner': 'ফার্মেসি মালিক',
      'safeAutoPayTitle': 'নিরাপদ অটো-পে লিমিট গার্ডরেল',
      'currentBalance': 'বর্তমান অটো-পে লিমিট',
      'addAmount': '+ টাকা যোগ করুন',
      'topUpSuccess': 'সফলভাবে টাকা যোগ করা হয়েছে!',
      'tabTriage': 'পরামর্শ',
      'tabStores': 'ফার্মেসি',
      'tabOrders': 'অর্ডার',
      'tabCard': 'হেলথ কার্ড',
      'tabSos': 'জরুরী',
      'signOutBtn': 'লগ আউট',
      'emergencyBtn': 'জরুরী SOS',
      'micTap': 'কথা বলতে মাইকে চাপ দিন',
      'micListening': 'শুনছি... এখন বলুন',
      'consultBtn': 'এআই পরামর্শ নিন',
      'changeLocationBtn': 'স্থান পরিবর্তন করুন 📍',
      'btnAutoDetectGps': '📍 জিপিএস দিয়ে স্থান নির্ধারণ',
      'saveLocationBtn': 'স্থান সংরক্ষণ করুন',
      'inStock': 'স্টক আছে',
      'orderDelivery': 'অর্ডার করুন',
      'healthCardTitle': '🛡️ স্বাস্থ্য কার্ড ও নিরাপত্তা',
      'editProfileBtn': '✏️ কার্ড সম্পাদনা করুন',
      'saveChangesBtn': '✓ সংরক্ষণ করুন',
      'loginGoogle': 'গুগল দিয়ে সাইন ইন করুন',
      'loginEmailDirect': 'ইমেল দিয়ে সরাসরি লগইন করুন',
    },
    'mr': {
      'brandTitle': 'मेडीकनेक्ट',
      'brandSubtitle': 'एआय आरोग्य सहाय्यक आणि फार्मसी',
      'guardLabel': 'सुरक्षा',
      'verifiedPatient': 'सत्यापित रुग्ण',
      'storeOwner': 'फार्मसी मालक',
      'safeAutoPayTitle': 'सुरक्षित ऑटो-पे मर्यादा',
      'currentBalance': 'सध्याची ऑटो-पे मर्यादा',
      'addAmount': '+ रक्कम जोडा',
      'topUpSuccess': 'रक्कम यशस्वीरित्या जोडली गेली!',
      'tabTriage': 'सल्ला',
      'tabStores': 'फार्मसी',
      'tabOrders': 'ऑर्डर्स',
      'tabCard': 'हेल्थ कार्ड',
      'tabSos': 'तातडीची मदत',
      'signOutBtn': 'लॉग आउट',
      'emergencyBtn': 'तातडीची मदत SOS',
      'micTap': 'बोलण्यासाठी माइक दाबा',
      'micListening': 'ऐकत आहे... आता बोला',
      'consultBtn': 'एआय सल्ला घ्या',
      'changeLocationBtn': 'स्थान बदला 📍',
      'btnAutoDetectGps': '📍 जीपीएस द्वारे स्थान शोधा',
      'saveLocationBtn': 'डिलिव्हरी पत्ता जतन करा',
      'inStock': 'स्टॉक उपलब्ध',
      'orderDelivery': 'डिलिव्हरीसाठी ऑर्डर करा',
      'healthCardTitle': '🛡️ सुरक्षित हेल्थ कार्ड',
      'editProfileBtn': '✏️ हेल्थ कार्ड संपादित करा',
      'saveChangesBtn': '✓ जतन करा',
      'loginGoogle': 'गुगल सह लॉगिन करा',
      'loginEmailDirect': 'ईमेल द्वारे थेट लॉगिन करा',
    }
  };
}

// Global convenience helper
String tr(BuildContext context, String key, [String? fallback]) {
  try {
    return AppLocalization().t(key, fallback);
  } catch (_) {
    return fallback ?? key;
  }
}
